services:
  app:
    image: passport-manager-app
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:8080
    depends_on:
      db:
       condition: service_healthy
      cache:
       condition: service_healthy

    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/opencirc
      DATABASE_USER: postgres
      DATABASE_PASSWORD: opencirc
      REDIS_HOST: cache
      REDIS_PORT: 6379
    networks:
      - spring-net
    restart: always

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: opencirc
      POSTGRES_DB: opencirc
    ports:
      - 5435:5432
    container_name: postgresql
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - spring-net

  cache:
    image: redis
    container_name: cache
    ports:
      - 6381:6379
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - spring-net

volumes:
  db_data:
  redisdata:

networks:
  spring-net:
