FROM maven:3.9.6-eclipse-temurin-21-alpine

WORKDIR /app

COPY pom.xml .

COPY src ./src

EXPOSE 8080

# Run in dev mode with hot reload
CMD ["mvn", "spring-boot:run", "-Dspring-boot.run.fork=false", "-Dspring.devtools.restart.enabled=true", "-Dmaven.test.skip=true"]
