spring.application.name=PassportManager
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
#spring.datasource.url=jdbc:postgresql://localhost:5433/opencirc
#spring.datasource.username=postgres
#spring.datasource.password=opencirc
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.platform=postgres

# JPA properties for Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

# Redis Configuration
#spring.redis.host=localhost
#spring.redis.port=6379

#bsDD Configurations
bsDD.class.searchText.url=https://api.bsdd.buildingsmart.org/api/Class/Search/v1
bsDD.classDetails.url=https://api.bsdd.buildingsmart.org/api/Class/v1
bsDD.propertiesWithDetail.url=https://api.bsdd.buildingsmart.org/api/Property/v4
bsDD.textSearch.url=https://api.bsdd.buildingsmart.org/api/TextSearch/v2

#OpenAPI Configuration
springdoc.api-docs.title=Opencirc API

spring.config.additional-location=classpath:/DataDictionary_Mapping/bsDD_Mapping.properties

company.name=opencirc

#JWT
jwt.access.token.expiration.time=15
jwt.refresh.token.expiration.time=1440

auth.register.url=/api/auth/register
auth.login.url=/api/auth/login

secret.encryption.key=kgAG8rSojLyXZLyB4O8Zwp/+Hgb+3a95RY31fiL3vDg=

server.port=8080

spring.shell.interactive.enabled=true