spring.application.name=PassportManager
spring.datasource.url=jdbc:postgresql://localhost:5436/opencirc?sslmode=disable
spring.datasource.username=postgres
spring.datasource.password=opencirc
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA properties for Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6380

#bsdd Configurations
bsdd.class.searchByText.url=http://localhost:8089/bsdd/api/Class/Search/v1
bsdd.class.details.url=http://localhost:8089/api/Class/v1
bsdd.textSearch.url=http://localhost:8089/bsdd/api/TextSearch/v2

spring.config.additional-location=classpath:/bsdd/bsdd.properties

company.name=opencirc

#JWT
jwt.access.token.expiration.time=15
jwt.refresh.token.expiration.time=1440

auth.register.url=/api/auth/register
auth.login.url=/api/auth/login


spring.shell.interactive.enabled=false
