spring.application.name=PassportManager
spring.datasource.url=jdbc:postgresql://localhost:5432/opencirc
spring.datasource.username=postgres
spring.datasource.password=opencirc
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA properties for Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.redis.host=localhost
spring.redis.port=6379


#bsDD Configurations
bsDD.class.searchText.url=https://api.bsdd.buildingsmart.org/api/Class/Search/v1
bsDD.classDetails.url=https://api.bsdd.buildingsmart.org/api/Class/v1
bsDD.propertiesWithDetail.url=https://api.bsdd.buildingsmart.org/api/Property/v4
bsDD.textSearch.url=https://api.bsdd.buildingsmart.org/api/TextSearch/v2

#OpenAPI Configuration
springdoc.api-docs.title=Opencirc API

spring.config.additional-location=classpath:/DataDictionary_Mapping/bsDD_Mapping.properties

company.name=opencirc

