spring.application.name=PassportManager
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.platform=postgres

# JPA properties for Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Redis Configuration
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

#bsdd Configurations
bsdd.class.searchText.url=https://api.bsdd.buildingsmart.org/api/Class/Search/v1
bsdd.classDetails.url=https://api.bsdd.buildingsmart.org/api/Class/v1
bsdd.textSearch.url=https://api.bsdd.buildingsmart.org/api/TextSearch/v2

spring.config.import=classpath:/DataDictionary_Mapping/bsdd.properties

company.name=opencirc

#JWT
jwt.access.token.expiration.time=100000
jwt.refresh.token.expiration.time=300000

auth.register.url=/api/auth/register
auth.login.url=/api/auth/login

secret.encryption.key=kgAG8rSojLyXZLyB4O8Zwp/+Hgb+3a95RY31fiL3vDg=

server.port=8080

spring.shell.interactive.enabled=true


#Seed
seed.passport.max-level=5
seed.passport.children-per-level=3
seed.passport.properties-count-to-select=2
seed.user.default-password=Password123!
seed.passport.templates.path=/templates/bsdd_templates.json
seed.passport.uris=https://identifier.buildingsmart.org/uri/etim/etim/10.0/class/EG000001,\
https://identifier.buildingsmart.org/uri/etim/etim/10.0/class/EC000003,\
https://identifier.buildingsmart.org/uri/etim/etim/10.0/class/EC000007,\
https://identifier.buildingsmart.org/uri/etim/etim/10.0/class/EC000017,\
https://identifier.buildingsmart.org/uri/etim/etim/10.0/class/EC000018,\
https://identifier.buildingsmart.org/uri/etim/etim/10.0/class/EC000019,\
https://identifier.buildingsmart.org/uri/etim/etim/10.0/class/EC000008,\
https://identifier.buildingsmart.org/uri/etim/etim/10.0/class/EC000020

#flyway configurations
spring.flyway.baseline-on-migrate=true
spring.flyway.validate-on-migrate=true
spring.flyway.clean-disabled=true


system.admin.full-name=System administrator
system.admin.email=admin@opencirc.org

#api secret key
api.secret.key=91j9LofQNontokx3taDyc4kcpDRej7FFjvY8kpoGXPw=

bsdd.table6.structure.template.path=dictionary_structure/br18B2T6-1.1.1.json
bsdd.table6.structure.output.cached.path=data/PlatformTreeStructureOutput.json
