#bsDD Field Mapping
bsdd=
property=
name=name
definition=definition
description=description
code=code,propertyCode
documentReference=documentReference
uri=uri
propertyUri=propertyUri
status=status,propertyStatus
propertySet=propertySet
subdivisionsOfUse=subdivisionsOfUse
uid=uid
versionDateUtc=versionDateUtc
versionNumber=versionNumber
revisionNumber=revisionNumber
replacingObjectCodes=replacingObjectCodes
replacedObjectCodes=replacedObjectCodes
countriesOfUse=countriesOfUse
activationDateUtc=activationDateUtc
dictionaryUri=dictionaryUri,propertyDictionaryUri
qudtCodes=qudtCodes
connectedPropertyCodes=connectedPropertyCodes
dataType=dataType
units=units
propertyValueKind=propertyValueKind
physicalQuantity=physicalQuantity
dimension=dimension
dimensionLength=dimensionLength
dimensionMass=dimensionMass
dimensionTime=dimensionTime
dimensionElectricCurrent=dimensionElectricCurrent
dimensionThermodynamicTemperature=dimensionThermodynamicTemperature
dimensionAmountOfSubstance=dimensionAmountOfSubstance
dimensionLuminousIntensity=dimensionLuminousIntensity
propertyCode=propertyCode
propertyDictionaryName=propertyDictionaryName
propertyDictionaryUri=propertyDictionaryUri
propertyUri=propertyUri
propertySet=propertySet
propertyStatus=propertyStatus
allowedValues=allowedValues
sortNumber=sortNumber
referenceCode=referenceCode
synonyms=synonyms
parentClassReference=parentClassReference
