name: Lint (staging)
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
jobs:
  lint-and-check-formatting:
    name: Lint and check formatting
    uses: ./.github/workflows/lint-jobs.yml
    with:
      environment: staging
    secrets: inherit
    permissions:
      contents: "read"
      id-token: "write"
      pull-requests: "write"
      checks: "write"
